### ISSUE TITLE
Error: Could not find or load main class com.google.gwt.dev.codeserver.CodeServer

### ISSUE THREAD

**Issue by natros** [tbroyer/gwt-maven-plugin#21]
Hi,

My configuration is basically this:

```xml
<packaging>gwt-app</packaging>

    <dependencies>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-user</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-codeserver</artifactId>
            <version>2.7.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <target>1.7</target>
                    <source>1.7</source>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>1.0-beta-1</version>
                <extensions>true</extensions>
                <configuration>
                    <moduleName>pt.ipb.gwt.demo.Demo</moduleName>
                    <moduleShortName>demo</moduleShortName>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

`mvn clean install` compiles without errors.
`mvn gwt:codeserver` complains that cannot find CodeServer. 

```
[INFO] --- gwt-maven-plugin:1.0-beta-1:codeserver (default-cli) @ gwt-demo ---
[WARNING] Error: Could not find or load main class com.google.gwt.dev.codeserver.CodeServer
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.358 s
[INFO] Finished at: 2015-04-18T17:22:45+01:00
[INFO] Final Memory: 13M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-beta-1:codeserver (default-cli) on project gwt-demo: GWT Compiler exited with status 1 -> [Help 1]
```

Am I missing something?

Thanks.

**Comment by tbroyer** [comment]
Can you copy/paste the output of `mvn -v` and also run `gwt:codeserver` with `-X` and look at (or copy/paste here) the lines that start with `Arguments:`  and `Classpath:`?

**Comment by natros** [comment]
Hi

```
mvn --version -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/Cellar/maven32/3.2.5/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.3", arch: "x86_64", family: "mac"
```

```
[DEBUG]   (f) project = MavenProject: pt.ipb.gwt.demo:gwt-demo:0.1.0-SNAPSHOT @ /Users/fsousa/Projects/exemplos/gwt-demo/pom.xml
[DEBUG] -- end configuration --
[DEBUG] Arguments: com.google.gwt.dev.codeserver.CodeServer -logLevel DEBUG -workDir gwt/codeserver -allowMissingSrc
[DEBUG] Classpath: 
[WARNING] Error: Could not find or load main class com.google.gwt.dev.codeserver.CodeServer
```

the project
https://dl.dropboxusercontent.com/u/5176435/gwt-demo.tar.gz

Thanks.

**Comment by branflake2267** [comment]
Looks like the codeserver wasn't loaded into the classpath. Adding it as a dependency should do the trick. Maybe something went haywire, adding -U sometimes helps.

**Comment by natros** [comment]
you mean this?
```xml
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>1.0-beta-1</version>
                <extensions>true</extensions>
                <configuration>
                    <moduleName>pt.ipb.gwt.demo.Demo</moduleName>
                    <moduleShortName>demo</moduleShortName>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.google.gwt</groupId>
                        <artifactId>gwt-codeserver</artifactId>
                        <version>2.7.0</version>
                    </dependency>
                    <dependency>
                        <groupId>com.google.gwt</groupId>
                        <artifactId>gwt-dev</artifactId>
                        <version>2.7.0</version>
                    </dependency>
                </dependencies>
            </plugin>
```

mvn -U -X gwt:codeserver

```
---
[DEBUG]   (f) project = MavenProject: pt.ipb.gwt.demo:gwt-demo:0.1.0-SNAPSHOT @ /Users/fsousa/Projects/exemplos/gwt-demo/pom.xml
[DEBUG] -- end configuration --
[DEBUG] Arguments: com.google.gwt.dev.codeserver.CodeServer -logLevel DEBUG -workDir gwt/codeserver -allowMissingSrc
[DEBUG] Classpath: 
[WARNING] Error: Could not find or load main class com.google.gwt.dev.codeserver.CodeServer
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.649 s
[INFO] Finished at: 2015-04-19T08:47:13+01:00
[INFO] Final Memory: 14M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-beta-1:codeserver (default-cli) on project gwt-demo: GWT Compiler exited with status 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-beta-1:codeserver (default-cli) on project gwt-demo: GWT Compiler exited with status 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.apache.maven.plugin.MojoExecutionException: GWT Compiler exited with status 1
	at net.ltgt.gwt.maven.CodeServerMojo.execute(CodeServerMojo.java:253)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 25 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by tbroyer** [comment]
Bug reproduced with the sample project. I had only tested with multi-module projects, and your demo project has a single module. Now I know what to do today ;-)
Thanks for the report and the repro case.

**Comment by tbroyer** [comment]
Apparently fixed by f361ab4dafb39ed503c43e697396d2622636d71d

Could you try with 1.0-SNAPSHOT?

**Comment by natros** [comment]
It's working.

Thank you!

**Comment by crispi** [comment]
I pulled down 1.0-rc-9 which looks like it contains your fix - but am still getting that error. 

`			<plugin>
				<groupId>net.ltgt.gwt.maven</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<version>1.0-rc-9</version>
				<extensions>true</extensions>
				<dependencies>
					<dependency>
						<groupId>com.google.gwt</groupId>
						<artifactId>gwt-dev</artifactId>
						<version>2.1.1</version>
					</dependency>
					<dependency>
						<groupId>com.google.gwt</groupId>
						<artifactId>gwt-user</artifactId>
						<version>2.1.1</version>
					</dependency>
				</dependencies>
				<configuration>
					<moduleName>com.autoniq.AutoniqAdmin</moduleName>
					<logLevel>TRACE</logLevel>
					<sourceLevel>1.8</sourceLevel>
				</configuration>
				<executions>
					<execution>
						<id>default-deploy</id>
						<phase>none</phase>
					</execution>
				</executions>
			</plugin>`

Unfortunately this is an old codebase, and we can't move beyond 2.1.1, and there is no gwt-codeserver jar for that version.

**Comment by tbroyer** [comment]
@crispi Two things:

 1. adding GWT as dependencies of the plugin is totally useless. This plugin uses project dependencies; Mojo's plugin uses plugin dependencies which might be why you did that.
 2. GWT 2.1.1 (wow, that's 7 years old already!) didn't have superdevmode (that was first added in GWT 2.5, two years later), so you won't be able to use `gwt:codeserver`, only `gwt:devmode`. But please note that this plugin is only guaranteed to work with the last two versions of GWT (and 1.0-rc-9 has only been tested with the last 3: 2.8.0, 2.8.1, and 2.8.2); if it doesn't work for you, then you'll have to use Mojo's plugin.

**Comment by crispi** [comment]
@tbroyer thanks - I figured out that I need to add compile scope to the gwt-dev dependency. Yes - the age of the plugin is a challenge - the whole app is a challenge :) Unfortunately we have to hang on to it while we rewrite the whole thing without GWT and are trying to automate the build process. I've ended up going in the direction of pulling down your plugin and making some custom changes just so we can get this working.
