### ISSUE TITLE
DevMode, `gwt-lib` dependency and re-compiling changes

### ISSUE THREAD

**Issue by timeu** [tbroyer/gwt-maven-plugin#31]
I am not sure if this is a bug or by design:

I created a reactor project for a GWT library which contains 2 modules:
- The library (packaging: `gwt-lib`) itself 
- A sample gwt app (packaging: `gwt-app`) as a showcase. 

Initially the sample gwt app had a simple dependency to the library (no classifier and no type declared). However when I run `mvn gwt:devmode` from my reactor project, changes to the library code (`gwt-lib`) are not picked up (re-compiled). Only changes to the sample app are re-compiled. 

The debug output shows the following line: 
```
[DEBUG] Ignoring com.github.timeu.dygraphs-gwt:dygraphs-gwt:jar:1.0.0-SNAPSHOT; neither a java-source, gwt-lib or jar:sources.
```

If I add a second dependency to the library with a classifier of type `sources` or with a  type of `gwt-lib` changes to the library will be properly re-compiled. 
I looked into the documentation and the only thing regarding this, was here: 
https://tbroyer.github.io/gwt-maven-plugin/artifact-handlers.html

I also looked into the integration tests and only found the type of the dependency to be set to `gwt-lib` here: https://github.com/tbroyer/gwt-maven-plugin/blob/2877b61bbd010cd83206482680d290f20654325c/src/it/e2e/e2e-client/pom.xml#L20

This is with JDK 1.8.0_45, Maven 3.2.1 and gwt-maven-plugin 1.0-rc-2

**Comment by tbroyer** [comment]
Yes, sources from other projects in the reactor build are only added to the classpath by `gwt:codeserver` (and `gwt:devmode`) for dependencies that are known to contain sources: `<classifier>sources</classifier>` or `<type>gwt-lib</type>`. If you don't include `<type>gwt-lib</type>`, Maven assumes `<type>jar</type>` and the plugin assumes it only contains compiled classes (and resources).
Note that `<type>gwt-lib</type>` in a dependency doesn't necessarily mean that the project has/had `<packaging>gwt-lib</packaging>`. Those two `gwt-lib` have the same name but are different things as far as Maven is concerned (and similarly for the built-in `jar`, `war`, etc.)

Leaving this issue open as a reminder that the documentation needs improvement.

**Comment by timeu** [comment]
Great, thanks for clarifying. 

Along these lines:   
If I specify the dependency to the library in the sample app twice (one time with type `gwt-lib` and one time with `jar`) I get following error if I run `mvn clean compile` on the reactor project: 
```
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-2:generate-module (default-generate-module) on project dygraphs-gwt-sample: Execution default-generate-module of goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-2:generate-module failed. NullPointerException -> [Help 1]
....
Caused by: java.lang.NullPointerException
        at net.ltgt.gwt.maven.GenerateModuleMojo.generateInheritsFromDependencies(GenerateModuleMojo.java:242)

```
Not sure if this is a separate issue.

**Comment by tbroyer** [comment]
Yes it's a separate issue (likely a bug, probq due to changes in Maven in recent versions).

**Comment by tbroyer** [comment]
Fixed by 69ac0f3

**Comment by timeu** [comment]
Sorry to spam this issue (isn't really a separate issue) but in case somebody ran into the same issue:

IntelliJ won't import dependencies if they are using with the `gwt-lib` type. To fix this, one has to go to `FIle -> Settings -> Maven -> Importing`  and add `gwt-lib` to the list of automatically imported dependencies.

**Comment by mahoe** [comment]
> Sorry to spam this issue (isn't really a separate issue) but in case somebody ran into the same issue:
> 
> IntelliJ won't import dependencies if they are using with the `gwt-lib` type. To fix this, one has to go to `FIle -> Settings -> Maven -> Importing` and add `gwt-lib` to the list of automatically imported dependencies.

If we call it a problem then it's still present. I fugured out that the NPE happens i.e. if you mess up the dependencies in your pom.xml with two entries for the same dependency (one with type gwt-lib and the second without any classifier). The plugin version I used for that is 1.0.0, GWT version 2.9.0, maven 3.6.3.

...just wanted to give my two cents here if someone comes by with the same problem.
